"use client";

import { useEffect, useMemo, useState } from "react";
import { FplData, FplPlayer, bestXi, eventTotals, fetchFplData, futureEvents, isValidSquad, optimizeSquad, playerProjection, savedSquad } from "../lib/fpl";
import { persist } from "../lib/persistence";

function useOfficialFpl(){const[data,setData]=useState<FplData|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);const load=async()=>{setLoading(true);setError("");try{setData(await fetchFplData())}catch(e){setError(e instanceof Error?e.message:"Official FPL data unavailable")}finally{setLoading(false)}};useEffect(()=>{load()},[]);return{data,error,loading,load}}
function Source({data,loading,onRefresh}:{data:FplData;loading:boolean;onRefresh:()=>void}){return <section className="live-source"><div><span className="live-dot"/><b>OFFICIAL FPL DATA</b><small>Auto-refreshes every 5 minutes · updated {new Date(data.updatedAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</small></div><button onClick={onRefresh} disabled={loading}>{loading?"Refreshing…":"Refresh now"}</button></section>}
function State({loading,error,retry}:{loading:boolean;error:string;retry:()=>void}){return <div className={`live-state ${error?"error":""}`}>{loading&&!error?<><span className="live-spinner"/><b>Loading official FPL data…</b></>:<><b>Official data unavailable</b><p>{error}</p><button onClick={retry}>Try again</button></>}</div>}

const sortOptions:[keyof FplPlayer|string,string][]=[["projected","Projected points"],["price","Price"],["totalPoints","Points scored"],["eventPoints","Latest GW points"],["goals","Goals"],["assists","Assists"],["expectedGoals","Expected goals (xG)"],["expectedAssists","Expected assists (xA)"],["expectedGoalInvolvements","xGI"],["minutes","Minutes"],["starts","Starts"],["cleanSheets","Clean sheets"],["bonus","Bonus"],["form","Form"],["selectedBy","Ownership"],["ictIndex","ICT index"]];
export function LivePlayers(){
  const{data,error,loading,load}=useOfficialFpl();const[query,setQuery]=useState("");const[position,setPosition]=useState("ALL");const[team,setTeam]=useState("ALL");const[sort,setSort]=useState("projected");const[direction,setDirection]=useState<"desc"|"asc">("desc");
  const events=data?futureEvents(data,1):[];const first=events[0]?.id;
  const rows=useMemo(()=>data?data.players.filter(p=>(position==="ALL"||p.positionShort===position)&&(team==="ALL"||String(p.teamId)===team)&&(`${p.name} ${p.firstName} ${p.secondName}`).toLowerCase().includes(query.toLowerCase())).map(player=>({player,projected:first?playerProjection(player,first,data.fixtures,first):0})).sort((a,b)=>{const av=sort==="projected"?a.projected:Number(a.player[sort as keyof FplPlayer])||0;const bv=sort==="projected"?b.projected:Number(b.player[sort as keyof FplPlayer])||0;return direction==="desc"?bv-av:av-bv}):[],[data,position,team,query,sort,direction,first]);
  if(!data)return <State loading={loading} error={error} retry={load}/>;
  return <div className="live-builder"><Source data={data} loading={loading} onRefresh={load}/><section className="data-intro"><div><span>2026/27 PLAYER DATABASE</span><h2>{data.players.length} official players. Zero placeholders.</h2><p>{data.seasonStatsThrough?`Points, goals, assists, xG, xA and minutes are aggregated from official 2026/27 live data through GW${data.seasonStatsThrough}.`:`The new season has no started gameweeks yet, so 2026/27 points, goals, xG and xA correctly begin at zero.`} Prices, clubs and availability still update live.</p></div><strong>{rows.length}<small>players shown</small></strong></section><div className="advanced-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search any player…"/><select value={position} onChange={e=>setPosition(e.target.value)}><option value="ALL">All positions</option>{data.rules.positions.map(p=><option key={p.id} value={p.short}>{p.short}</option>)}</select><select value={team} onChange={e=>setTeam(e.target.value)}><option value="ALL">All teams</option>{data.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}>{sortOptions.map(([value,label])=><option value={value} key={String(value)}>Sort: {label}</option>)}</select><button onClick={()=>setDirection(x=>x==="desc"?"asc":"desc")}>{direction==="desc"?"Highest first ↓":"Lowest first ↑"}</button></div><section className="mega-table"><div className="mega-head"><span>PLAYER</span><button onClick={()=>setSort("price")}>PRICE</button><button onClick={()=>setSort("projected")}>xPTS</button><button onClick={()=>setSort("totalPoints")}>PTS</button><button onClick={()=>setSort("goals")}>G</button><button onClick={()=>setSort("assists")}>A</button><button onClick={()=>setSort("expectedGoals")}>xG</button><button onClick={()=>setSort("expectedAssists")}>xA</button><button onClick={()=>setSort("minutes")}>MINS</button><button onClick={()=>setSort("bonus")}>BONUS</button><button onClick={()=>setSort("selectedBy")}>OWN%</button></div>{rows.map(({player,projected})=><div className="mega-row" key={player.id}><b>{player.name}<small>{player.teamShort} · {player.positionShort}</small></b><span>£{player.price.toFixed(1)}</span><strong>{projected.toFixed(1)}</strong><span>{player.totalPoints}</span><span>{player.goals}</span><span>{player.assists}</span><span>{player.expectedGoals.toFixed(2)}</span><span>{player.expectedAssists.toFixed(2)}</span><span>{player.minutes}</span><span>{player.bonus}</span><span>{player.selectedBy.toFixed(1)}</span></div>)}</section></div>
}

export function LiveFixtures(){
  const{data,error,loading,load}=useOfficialFpl();const[horizon,setHorizon]=useState(5);if(!data)return <State loading={loading} error={error} retry={load}/>;const events=futureEvents(data,horizon);const teamMap=new Map(data.teams.map(t=>[t.id,t]));
  const table=data.teams.map(team=>{const cells=events.map(event=>{const games=data.fixtures.filter(f=>f.event===event.id&&(f.teamH===team.id||f.teamA===team.id));return games.map(game=>{const home=game.teamH===team.id;const opponent=teamMap.get(home?game.teamA:game.teamH);return{label:`${opponent?.short??"—"} ${home?"H":"A"}`,difficulty:home?game.teamHDifficulty:game.teamADifficulty,kickoff:game.kickoff}})});const diffs=cells.flat().map(c=>c.difficulty);return{team,cells,average:diffs.length?diffs.reduce((a,b)=>a+b,0)/diffs.length:6}}).sort((a,b)=>a.average-b.average);
  const doubles=events.map(event=>({event,teams:data.teams.filter(t=>data.fixtures.filter(f=>f.event===event.id&&(f.teamH===t.id||f.teamA===t.id)).length>1)})).filter(x=>x.teams.length);const blanks=events.map(event=>({event,teams:data.teams.filter(t=>data.fixtures.filter(f=>f.event===event.id&&(f.teamH===t.id||f.teamA===t.id)).length===0)})).filter(x=>x.teams.length);
  const columns=`130px 65px repeat(${Math.max(1,events.length)},minmax(95px,1fr))`;
  return <div className="live-builder"><Source data={data} loading={loading} onRefresh={load}/><div className="fixture-controls"><div><span>HORIZON</span>{[3,5,8].map(n=><button className={horizon===n?"active":""} onClick={()=>setHorizon(n)} key={n}>{n} GW</button>)}</div><div><small>CONFIRMED DOUBLES</small><b>{doubles.length?doubles.map(x=>x.event.name).join(", "):"None in range"}</b></div><div><small>CONFIRMED BLANKS</small><b>{blanks.length?blanks.map(x=>x.event.name).join(", "):"None in range"}</b></div></div><section className="fixture-board"><header style={{gridTemplateColumns:columns}}><span>TEAM</span><span>AVG FDR</span>{events.map(e=><span key={e.id}>{e.name.replace("Gameweek ","GW")}</span>)}</header>{table.map(row=><div className="fixture-team-row" style={{gridTemplateColumns:columns}} key={row.team.id}><b>{row.team.short}<small>{row.team.name}</small></b><strong>{row.average===6?"—":row.average.toFixed(2)}</strong>{row.cells.map((games,i)=><div className="fixture-cell" key={events[i].id}>{games.length?games.map((game,n)=><span className={`fdr-${game.difficulty}`} key={n}>{game.label}<small>FDR {game.difficulty}</small></span>):<span className="blank">BLANK</span>}</div>)}</div>)}</section><section className="match-centre"><header><span>OFFICIAL FIXTURE LIST</span><h2>Every confirmed match and kickoff.</h2></header>{events.map(event=><div className="event-block" key={event.id}><b>{event.name}</b><small>Deadline {new Date(event.deadline).toLocaleString([],{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}</small><div>{data.fixtures.filter(f=>f.event===event.id).map(f=><article key={f.id}><span>{teamMap.get(f.teamH)?.short}</span><b>{f.finished?`${f.teamHScore} – ${f.teamAScore}`:"vs"}</b><span>{teamMap.get(f.teamA)?.short}</span><time>{f.kickoff?new Date(f.kickoff).toLocaleString([],{weekday:"short",hour:"2-digit",minute:"2-digit"}):"TBC"}</time></article>)}</div></div>)}</section></div>
}

export function LiveNews(){
  const{data,error,loading,load}=useOfficialFpl();const[filter,setFilter]=useState("ALL");const[query,setQuery]=useState("");if(!data)return <State loading={loading} error={error} retry={load}/>;const owned=new Set(savedSquad(data).map(p=>p.id));const news=data.players.filter(p=>p.news||p.status!=="a").filter(p=>(filter==="ALL"||filter==="SQUAD"&&owned.has(p.id)||filter==="DOUBT"&&p.chance!==null||filter==="UNAVAILABLE"&&["i","s","u"].includes(p.status))&&(`${p.name} ${p.teamName} ${p.news}`).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(b.newsAdded?Date.parse(b.newsAdded):0)-(a.newsAdded?Date.parse(a.newsAdded):0)||b.selectedBy-a.selectedBy);const movers=[...data.players].sort((a,b)=>(b.transfersIn-b.transfersOut)-(a.transfersIn-a.transfersOut)).slice(0,5);
  return <div className="live-builder"><Source data={data} loading={loading} onRefresh={load}/><section className="news-command"><div><span>AVAILABILITY COMMAND CENTRE</span><h2>{news.length} official player updates require attention.</h2><p>Player flags and availability notes come directly from FPL. We never invent quotes or pretend an unsourced rumour is confirmed.</p></div><div><b>{data.players.filter(p=>p.status!=="a").length}</b><small>flagged players</small></div></section><div className="news-controls"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search player, club or update…"/>{[["ALL","All updates"],["SQUAD","My squad"],["DOUBT","Doubts"],["UNAVAILABLE","Unavailable"]].map(([id,label])=><button className={filter===id?"active":""} onClick={()=>setFilter(id)} key={id}>{label}</button>)}</div><section className="official-news-list">{news.length?news.map(player=><article key={player.id}><div className={`news-status status-${player.status}`}>{player.chance!==null?`${player.chance}%`:player.status==="a"?"OK":"!"}</div><div><span>{owned.has(player.id)?"YOUR SQUAD · ":""}{player.teamShort} · {player.positionShort}</span><h3>{player.name}</h3><p>{player.news||"Flagged by the official FPL player feed. No additional note has been published."}</p><small>{player.newsAdded?`Updated ${new Date(player.newsAdded).toLocaleString()}`:"Official status currently has no timestamp"}</small></div><aside><b>£{player.price.toFixed(1)}m</b><span>{player.selectedBy.toFixed(1)}% owned</span><small>{player.transfersOut.toLocaleString()} transfers out</small></aside></article>):<div className="empty-news">No official updates match this filter.</div>}</section><section className="market-watch"><header><span>TRANSFER MARKET SIGNAL</span><h2>Most-bought players right now.</h2></header><div>{movers.map(p=><article key={p.id}><b>{p.name}<small>{p.teamShort} · {p.positionShort}</small></b><span>+{Math.max(0,p.transfersIn-p.transfersOut).toLocaleString()}</span><small>net transfers</small></article>)}</div></section></div>
}

type Chip="Wildcard"|"Free Hit"|"Bench Boost"|"Triple Captain";
export function LiveChips(){
  const{data,error,loading,load}=useOfficialFpl();const[selected,setSelected]=useState<Chip>("Wildcard");if(!data)return <State loading={loading} error={error} retry={load}/>;const events=futureEvents(data,8);const stored=savedSquad(data);const hasSquad=isValidSquad(stored,data);const baseline=hasSquad?stored:optimizeSquad(data,events.slice(0,5).map(e=>e.id));const clamp=(n:number)=>Math.max(1,Math.min(10,Math.round(n)));
  const rows=events.map((event,index)=>{const window=events.slice(index,index+5).map(e=>e.id);const oneBest=optimizeSquad(data,[event.id]);const oneXi=bestXi(oneBest,event.id,data.fixtures,event.id);const currentXi=bestXi(baseline,event.id,data.fixtures,event.id);const wc=optimizeSquad(data,window);const uplift=eventTotals(wc,window,data.fixtures).reduce((a,b)=>a+b,0)-eventTotals(baseline,window,data.fixtures).reduce((a,b)=>a+b,0);const xiBase=currentXi.players.reduce((s,p)=>s+playerProjection(p,event.id,data.fixtures,event.id),0);const squadAll=baseline.reduce((s,p)=>s+playerProjection(p,event.id,data.fixtures,event.id),0);const bench=Math.max(0,squadAll-xiBase);const freeHit=Math.max(0,oneXi.total-currentXi.total);const tc=oneXi.captain?playerProjection(oneXi.captain,event.id,data.fixtures,event.id):0;return{event,wildcard:{score:clamp(2+uplift/3),detail:hasSquad?`+${Math.max(0,uplift).toFixed(1)} projected pts vs your squad over 5 GWs`:"Build your squad to calculate personal uplift"},freeHit:{score:clamp(1+freeHit*1.1),detail:`+${freeHit.toFixed(1)} one-week pts vs current XI`},benchBoost:{score:clamp(bench/1.25),detail:`${bench.toFixed(1)} projected bench pts`},tripleCaptain:{score:clamp(2+tc/1.25),detail:`${oneXi.captain?.name??"—"} · ${tc.toFixed(1)} xPts`}}});const key=selected==="Wildcard"?"wildcard":selected==="Free Hit"?"freeHit":selected==="Bench Boost"?"benchBoost":"tripleCaptain";const best=[...rows].sort((a,b)=>b[key].score-a[key].score)[0];
  return <div className="live-builder"><Source data={data} loading={loading} onRefresh={load}/><div className="chip-selector">{(["Wildcard","Free Hit","Bench Boost","Triple Captain"] as Chip[]).map(chip=><button className={selected===chip?"active":""} onClick={()=>setSelected(chip)} key={chip}><span>{chip}</span><b>{Math.max(...rows.map(r=>r[chip==="Wildcard"?"wildcard":chip==="Free Hit"?"freeHit":chip==="Bench Boost"?"benchBoost":"tripleCaptain"].score))}/10</b><small>best upcoming score</small></button>)}</div><section className="chip-recommendation"><div><span>BEST WINDOW</span><h2>{best?.event.name??"No confirmed window"}</h2><p>{best?.[key].detail}</p></div><strong>{best?.[key].score??"—"}<small>/10</small></strong></section><section className="chip-week-table"><header><span>GAMEWEEK</span><span>DEADLINE</span><span>SCORE</span><span>{selected==="Triple Captain"?"BEST PLAYER":"MODELED VALUE"}</span><span>VERDICT</span></header>{rows.map(row=><div key={row.event.id}><b>{row.event.name}</b><time>{new Date(row.event.deadline).toLocaleDateString([],{day:"numeric",month:"short"})}</time><strong>{row[key].score}/10</strong><span>{row[key].detail}</span><em>{row[key].score>=8?"Excellent":row[key].score>=6?"Good":row[key].score>=4?"Average":"Avoid"}</em></div>)}</section><p className="model-note">Wildcard scores compare your saved 15-player squad against the best legal squad the model can construct for that five-gameweek window. Chip scores update whenever official fixtures, prices or player availability change.</p></div>
}

export function LivePointsModel(){
  const{data,error,loading,load}=useOfficialFpl();const[query,setQuery]=useState("");const[selected,setSelected]=useState<number|null>(null);if(!data)return <State loading={loading} error={error} retry={load}/>;const events=futureEvents(data,5);const candidates=data.players.filter(p=>(`${p.name} ${p.teamName}`).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.epNext-a.epNext).slice(0,12);const player=data.players.find(p=>p.id===(selected??candidates[0]?.id))??data.players[0];const projections=events.map(e=>playerProjection(player,e.id,data.fixtures,events[0]?.id));const availabilityPct=Math.round((player.chance!==null?player.chance/100:player.status==="a"?1:.3)*100);const recent=Math.max(.7,player.pointsPerGame*.48+player.form*.28+player.epNext*.24);
  return <div className="live-builder"><Source data={data} loading={loading} onRefresh={load}/><section className="model-search"><div><span>LIVE PLAYER MODEL</span><h2>Inspect the inputs, not just the answer.</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a player…"/><div>{candidates.map(p=><button className={p.id===player.id?"active":""} onClick={()=>setSelected(p.id)} key={p.id}>{p.name}<small>{p.teamShort}</small></button>)}</div></section><section className="model-hero"><div><span>{player.teamName} · {player.position} · £{player.price.toFixed(1)}m</span><h2>{player.name}</h2><p>{player.news||"Available according to the official FPL feed."}</p></div><strong>{projections[0]?.toFixed(1)??"—"}<small>next GW xPts</small></strong></section><div className="model-real-grid"><article><span>2026/27 OUTPUT</span><b>{player.totalPoints}</b><small>current-season points through GW{data.seasonStatsThrough}</small></article><article><span>GOAL THREAT</span><b>{player.goals} G · {player.expectedGoals.toFixed(2)} xG</b><small>{player.threat.toFixed(1)} threat index</small></article><article><span>CREATION</span><b>{player.assists} A · {player.expectedAssists.toFixed(2)} xA</b><small>{player.creativity.toFixed(1)} creativity</small></article><article><span>MINUTES</span><b>{player.minutes}</b><small>{player.starts} starts · {availabilityPct}% availability</small></article><article><span>BONUS</span><b>{player.bonus}</b><small>{player.bps} BPS</small></article><article><span>ICT</span><b>{player.ictIndex.toFixed(1)}</b><small>{player.influence.toFixed(1)} influence</small></article></div><section className="projection-path"><header><span>FIVE-GAMEWEEK PROJECTION</span><small>Official fixtures + current form/availability · FPL Edge fixture model</small></header><div>{events.map((event,i)=><article key={event.id}><span>{event.name}</span><b>{projections[i].toFixed(1)}</b><small>xPts</small></article>)}</div></section><section className="model-breakdown-live"><div><span>BASE PERFORMANCE</span><b>{recent.toFixed(2)}</b><p>{data.seasonStatsThrough?"Uses current-season official PPG, form and next-gameweek expectation.":"Before GW1, last-season PPG is used only as a projection prior; every displayed 2026/27 performance total remains zero."}</p></div><div><span>AVAILABILITY</span><b>{availabilityPct}%</b><p>Uses the official status and chance-of-playing flag. Uncertain players are discounted.</p></div><div><span>FIXTURE ADJUSTMENT</span><b>FDR-aware</b><p>Each confirmed fixture is adjusted for venue and official FPL difficulty. Doubles add; blanks score zero.</p></div></section></div>
}

type HistoryWeek={event:number;points:number;totalPoints:number;overallRank:number;gameweekRank:number;transfers:number;transferCost:number;pointsOnBench:number;value:number;bank:number;captain:string;captainRawPoints:number;captainContribution:number;viceCaptain:string;chip:string|null};
export function LiveHistory(){
  const[entry,setEntry]=useState("");const[data,setData]=useState<{updatedAt:string;manager:{id:number;name:string;teamName:string;overallPoints:number;overallRank:number};weeks:HistoryWeek[]}|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(false);useEffect(()=>{const saved=localStorage.getItem("fpl-edge-entry");if(saved){setEntry(saved);load(saved)}},[]);async function load(id=entry){if(!/^\d+$/.test(id.trim())){setError("Enter the number from your official FPL team URL.");return}setLoading(true);setError("");try{const response=await fetch(`/api/fpl/history?entry=${id.trim()}`,{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json.error||"Could not load history");setData(json);persist("fpl-edge-entry",id.trim())}catch(e){setError(e instanceof Error?e.message:"Could not load history")}finally{setLoading(false)}}const weeks=data?.weeks??[];const avg=weeks.length?weeks.reduce((s,w)=>s+w.points,0)/weeks.length:0;const captain=weeks.reduce((s,w)=>s+w.captainContribution,0);const bench=weeks.reduce((s,w)=>s+w.pointsOnBench,0);const hits=weeks.reduce((s,w)=>s+w.transferCost,0);
  return <div className="live-builder"><section className="history-connect"><div><span>OFFICIAL TEAM HISTORY</span><h2>Connect your FPL manager ID.</h2><p>Read-only. We use official finished-gameweek data and never ask for your password.</p></div><div><input value={entry} onChange={e=>setEntry(e.target.value.replace(/\D/g,""))} placeholder="e.g. 123456"/><button onClick={()=>load()} disabled={loading}>{loading?"Loading…":data?"Refresh history":"Connect history"}</button></div>{error&&<small>{error}</small>}</section>{data?<><section className="history-owner"><div><span>{data.manager.name}</span><h2>{data.manager.teamName}</h2><small>Manager ID {data.manager.id} · official data refreshed {new Date(data.updatedAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</small></div><div><b>{data.manager.overallPoints??"—"}</b><small>total points</small></div><div><b>{data.manager.overallRank?.toLocaleString()??"—"}</b><small>overall rank</small></div></section><div className="history-kpis"><article><span>AVG GW</span><b>{avg.toFixed(1)}</b></article><article><span>CAPTAIN POINTS</span><b>{captain}</b></article><article><span>BENCH POINTS</span><b>{bench}</b></article><article><span>POINTS SPENT</span><b>−{hits}</b></article></div>{weeks.length?<section className="history-live-table"><header><span>GW</span><span>POINTS</span><span>CAPTAIN</span><span>CAPTAIN PTS</span><span>BENCH</span><span>TRANSFERS</span><span>HIT</span><span>GW RANK</span><span>OVERALL RANK</span><span>CHIP</span></header>{[...weeks].reverse().map(w=><div key={w.event}><b>GW{w.event}</b><strong>{w.points}</strong><span>{w.captain}</span><span>{w.captainContribution}<small>{w.captainRawPoints} raw</small></span><span>{w.pointsOnBench}</span><span>{w.transfers}</span><span>{w.transferCost?`−${w.transferCost}`:"0"}</span><span>{w.gameweekRank?.toLocaleString()}</span><span>{w.overallRank?.toLocaleString()}</span><em>{w.chip||"—"}</em></div>)}</section>:<div className="history-empty"><b>No finished gameweeks yet.</b><p>Your official points, captain returns, bench points, transfers, hits, ranks and chips will appear automatically after FPL marks each gameweek finished.</p></div>}</>:<div className="history-empty"><b>No fake history.</b><p>Connect your official manager ID to replace the old demo rows with your real gameweek record.</p></div>}</div>
}
